
server:
  port: 3066

spring:
  redis:
#    host: 127.0.0.1
    host: localhost
    port: 6379
    timeout: 6000
#    password: firredisxy

# 引入logger日志相关配置
logging:
  config: classpath:logback-spring.xml

####### 其他内容的配置
## REDIS (RedisProperties)
## Redis数据库索引（默认为0）
#spring.redis.database=0
## Redis服务器地址
#spring.redis.host=localhost
## Redis服务器连接端口
#spring.redis.port=6379
## Redis服务器连接密码（默认为空）
#spring.redis.password=
## 连接池最大连接数（使用负值表示没有限制）
#spring.redis.jedis.pool.max-active=8
## 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.jedis.pool.max-wait=-1
## 连接池中的最大空闲连接
#spring.redis.jedis.pool.max-idle=8
## 连接池中的最小空闲连接
#spring.redis.jedis.pool.min-idle=0
## 连接超时时间（毫秒）
#spring.redis.timeout=5000
#
#redis:
## Redis数据库索引（默认为0）
#database: 0
## Redis服务器地址
#host: 127.0.0.1
## Redis服务器连接端口
#port: 6379
## Redis服务器连接密码（默认为空）
#password:
## 连接池最大连接数（使用负值表示没有限制）
#jedis:
#pool:
#max-active: 8
## 连接池最大阻塞等待时间（使用负值表示没有限制）
#max-idle: 8
## 连接池中的最大空闲连接
#max-wait: -1
## 连接池中的最小空闲连接
#min-idle: 0
## 连接超时时间（毫秒）
#timeout: 0